### PR TITLE
Transaction index + Back button when transaction

### LINKED ISSUE #209: Transactions : indicate how much tx and current tx index
DOD : 
- [ ] Schedule claim (aproving claim deposit -> schedule claim)
- [ ] Challenge claim (aproving challenge deposit -> challenge claim)
- [ ] Create quest (create quest -> fund quest only) [ONLY IF INITIAL FUND AMOUNT]
- [ ] Be able to back to the form after tx is completed (success or failed)

### PR DESCRIPTION
**Pull request by Corantin**
closes #209

### CODE REVIEW

**Review by kamikazebr — COMMENTED** [review]
# Nice!

image

----

# But


After click in the Back button it return to that screen, its not should close?
image

I wanted a back button if per example the transaction failed, to be able to resubmit a new with adjusting some fields

**Comment by Corantin** [comment]
> I wanted a back button if per example the transaction failed, to be able to resubmit a new with adjusting some fields

I wanted a back button if per example the transaction failed, to be able to resubmit a new with adjusting some fields

**Comment by Corantin** [comment]
> # Nice!
> image
> 
> # But
> After click in the Back button it return to that screen, its not should close? image


I wanted a back button if per example the transaction failed, to be able to resubmit a new with adjusting some fields

**Comment by kamikazebr** [comment]
> I wanted a back button if per example the transaction failed, to be able to resubmit a new with adjusting some fields. Do you think it's counter-intuitive? Any suggestions?

Humm idk. Maybe in the future we can just show back button if it failed? And keep the old data to be adjusted or resend?

yah it's counter intuitive, because the modal can be open for others places and back button looks like we will back there.

Not related but also we can add shortcut for example ESC to close modal will be good improvement immo.

**Comment by Corantin** [comment]
I can change it to only failed for sure.
There is escape to close only when button are modal are focused not inputs

**Pull request merged**
